[package]
name = "the_salvager"
version = "0.1.0"
authors = ["stephan <stephan@svoboda.or.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
